apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wkfd1llec-go 
  janus-idp.io/tekton: wkfd1llec-go
  backstage.io/kubernetes-id: wkfd1llec-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wkfd1llec-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml